# Generated by Django 3.0.5 on 2021-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='book_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Language'),
        ),
    ]
